version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  flyway:
      image: flyway/flyway
      command: -url=jdbc:postgresql://db:5432/mydb -user=user -password=password -connectRetries=60 migrate
      volumes:
        - ./sql:/flyway/sql
      depends_on:
        - db

  oapi-codegen:
    build:
      context: .
      dockerfile: Dockerfile.oapi-codegen
    volumes:
      - .:/app

  http-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
    depends_on:
      - db
    volumes:
      - ./client:/go/src/generated-client
    ports:
      - "8080:8080"
volumes:
  pgdata: