FROM golang:1.17-alpine

# Update apk and install postgresql-client and Git
RUN apk add --no-cache git postgresql-client

# Copy the Go source files to the container
COPY main.go /app/

# Set the working directory
WORKDIR /app

# Download dependencies and build the program
RUN go mod init mymodule
RUN go mod tidy
RUN go build -o my-program

# Run the program
CMD ["./my-program"]
